



/* cfortan headers for the DGELSD and DGELSY routines from LAPACK. For computing the
   minimum-norm solution to a (real, double precision) linear least square problem by
   singular value decomposition and complete orthogonal factorization respectively.

   The number 14 in PROTOCCALLSFSUB14 specifies 14 arguments.
*/

// Include the header file for fortran wrappers in C/C++
#include "generic/cfortran.h"

// SUBROUTINE DGELSD( M,N, NRHS, A, LDA, B, LDB, S, RCOND, RANK, WORK, LWORK, IWORK, INFO )
PROTOCCALLSFSUB14(DGELSD,dgelsd,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,DOUBLE,INT,DOUBLEV,INT,INTV,INT)
#define DGELSD(M,N,NRHS,A,LDA,B,LDB,S,RCOND,RANK,WORK,LWORK,IWORK,INFO) CCALLSFSUB14(DGELSD,dgelsd,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,DOUBLE,INT,DOUBLEV,INT,INTV,INT,M,N,NRHS,A,LDA,B,LDB,S,RCOND,RANK,WORK,LWORK,IWORK,INFO)


// SUBROUTINE DGELSY( M, N, NRHS, A, LDA, B, LDB, JPVT, RCOND, RANK, WORK, LWORK, INFO )
PROTOCCALLSFSUB13(DGELSY,dgelsy,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,INTV,DOUBLE,INT,DOUBLEV,INT,INT)
#define DGELSY(M,N,NRHS,A,LDA,B,LDB,JPVT,RCOND,RANK,WORK,LWORK,INFO) CCALLSFSUB13(DGELSY,dgelsy,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,INTV,DOUBLE,INT,DOUBLEV,INT,INT,M,N,NRHS,A,LDA,B,LDB,JVPT,RCOND,RANK,WORK,LWORK,INFO)
